products = Product.create([{ name: 'Almond Toe Court Shoes,
Patent Black', category:'Women’s Footwear', price:99, quantity: 5, image_url:'string.jpeg'},
{ name: 'Suede Shoes, Blue', category:'Women’s Footwear', price:42, quantity: 4, image_url:'string.jpeg'},
{ name: 'Leather Driver Saddle Loafers, Tan', category:'Men’s Footwear', price:34, quantity: 12, image_url:'string.jpeg'},
{ name: 'Flip flops, red', category:'Mens Footwear', price:19, quantity: 6, image_url:'string.jpeg'},
{ name: 'Flip flops, blue', category:'Men’s Footwear', price:19, quantity: 0, image_url:'string.jpeg'},
{ name: 'Gold Button Cardigan, Black', category:'Women’s Casualwear', price:167, quantity: 6, image_url:'string.jpeg'},
{ name: 'Cotton Shorts, Medium Red', category:'Women’s Casualwear', price:30, quantity: 5, image_url:'string.jpeg'},
{ name: 'Fine Stripe Short Sleeve Shirt, Grey', category:'Men’s Casualwear', price:49.99, quantity: 9, image_url:'string.jpeg'},
{ name: 'Fine Stripe Short Sleeve Shirt, Green', category:'Men’s Casualwear', price:39.99, quantity: 3, image_url:'string.jpeg'},
{ name: 'Sharkskin Waistcoat, Charcoal', category:'Men’s Formalwear', price:75, quantity: 2, image_url:'string.jpeg'},
{ name: 'Lightweight Patch Pocket Blazer, Deer', category:'Men’s Formalwear', price:175.50, quantity: 1, image_url:'string.jpeg'},
{ name: 'Bird Print Dress, Black', category:'Women’s Formalwear', price:270, quantity: 10, image_url:'string.jpeg'},
{ name: 'Mid Twist Cut-Out Dress, Pink', category:'Women’s Formalwear', price:540, quantity: 5, image_url:'string.jpeg'}])
